version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - 27027:27017
    volumes:
      - ./mongodb-data:/data/db
    container_name: 'local-mongo-datastore'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwer1234
      MONGO_INITDB_DATABASE: local-mongo
